### ISSUE TITLE
Attempt to increase "border word" list / Integrate other name detection (PDF)

### ISSUE THREAD

**Issue by JingLi201802** [JingLi201802/Taxonomic#15]

**Comment by JoshuaTrevor** [comment]
Rather than having separate lists for "beginning" and "ending" border words, I have instead implemented a dictionary approach using a file containing 58000 common English words. 

This approach has 2 major limitations:
- Scientific names which contain English words (eg if the author's surname is "Ransom") will be cropped
- The program may include extra non-english words adjacent to the name.

**Comment by afuchs1** [comment]
@JoshuaTrevor your note about limitation 1 above would seem to an issue.... we will need to look at the test results to see if this approach will work.

**Comment by JoshuaTrevor** [comment]
It definitely is not reliable enough at this stage and will need improvement, I have plans to address this in another issue: https://github.com/JingLi201802/Taxonomic/issues/30
